name: Docker Compose CI


on:
  push:
    branches: [ main, dev, prod ]
  pull_request:
    branches: [ main, dev, prod]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
